[[constraint]]
  name = "github.com/fatih/camelcase"
  version = "1.0.0"

[[constraint]]
  name = "github.com/leboncoin/structs"
  version = "v1.0.1_lbc"


[[constraint]]
  name = "github.com/faberia/goavro"
  version = "2.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
